# Generated by Django 4.1.3 on 2022-12-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='PhoneNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nonperishables',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nonperishables',
            name='Stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nonperishables',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perishables',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='perishables',
            name='Stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='perishables',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
