# Generated by Django 4.1.3 on 2023-01-02 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_customer_rename_complete_order_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='member',
            new_name='customer',
        ),
    ]
